// AUTO-GENERATED

#ifndef _GI_SOUP__CONSTANTS_HPP_
#define _GI_SOUP__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace Soup {

const gint ADDRESS_ANY_PORT_ = SOUP_ADDRESS_ANY_PORT;

const gchar ADDRESS_FAMILY_[] = SOUP_ADDRESS_FAMILY;

const gchar ADDRESS_NAME_[] = SOUP_ADDRESS_NAME;

const gchar ADDRESS_PHYSICAL_[] = SOUP_ADDRESS_PHYSICAL;

const gchar ADDRESS_PORT_[] = SOUP_ADDRESS_PORT;

const gchar ADDRESS_PROTOCOL_[] = SOUP_ADDRESS_PROTOCOL;

const gchar ADDRESS_SOCKADDR_[] = SOUP_ADDRESS_SOCKADDR;

const gchar AUTH_DOMAIN_ADD_PATH_[] = SOUP_AUTH_DOMAIN_ADD_PATH;

const gchar AUTH_DOMAIN_BASIC_AUTH_CALLBACK_[] = SOUP_AUTH_DOMAIN_BASIC_AUTH_CALLBACK;

const gchar AUTH_DOMAIN_BASIC_AUTH_DATA_[] = SOUP_AUTH_DOMAIN_BASIC_AUTH_DATA;

const gchar AUTH_DOMAIN_DIGEST_AUTH_CALLBACK_[] = SOUP_AUTH_DOMAIN_DIGEST_AUTH_CALLBACK;

const gchar AUTH_DOMAIN_DIGEST_AUTH_DATA_[] = SOUP_AUTH_DOMAIN_DIGEST_AUTH_DATA;

const gchar AUTH_DOMAIN_FILTER_[] = SOUP_AUTH_DOMAIN_FILTER;

const gchar AUTH_DOMAIN_FILTER_DATA_[] = SOUP_AUTH_DOMAIN_FILTER_DATA;

const gchar AUTH_DOMAIN_GENERIC_AUTH_CALLBACK_[] = SOUP_AUTH_DOMAIN_GENERIC_AUTH_CALLBACK;

const gchar AUTH_DOMAIN_GENERIC_AUTH_DATA_[] = SOUP_AUTH_DOMAIN_GENERIC_AUTH_DATA;

const gchar AUTH_DOMAIN_PROXY_[] = SOUP_AUTH_DOMAIN_PROXY;

const gchar AUTH_DOMAIN_REALM_[] = SOUP_AUTH_DOMAIN_REALM;

const gchar AUTH_DOMAIN_REMOVE_PATH_[] = SOUP_AUTH_DOMAIN_REMOVE_PATH;

const gchar AUTH_HOST_[] = SOUP_AUTH_HOST;

const gchar AUTH_IS_AUTHENTICATED_[] = SOUP_AUTH_IS_AUTHENTICATED;

const gchar AUTH_IS_FOR_PROXY_[] = SOUP_AUTH_IS_FOR_PROXY;

const gchar AUTH_REALM_[] = SOUP_AUTH_REALM;

const gchar AUTH_SCHEME_NAME_[] = SOUP_AUTH_SCHEME_NAME;

const gint CHAR_HTTP_CTL_ = SOUP_CHAR_HTTP_CTL;

const gint CHAR_HTTP_SEPARATOR_ = SOUP_CHAR_HTTP_SEPARATOR;

const gint CHAR_URI_GEN_DELIMS_ = SOUP_CHAR_URI_GEN_DELIMS;

const gint CHAR_URI_PERCENT_ENCODED_ = SOUP_CHAR_URI_PERCENT_ENCODED;

const gint CHAR_URI_SUB_DELIMS_ = SOUP_CHAR_URI_SUB_DELIMS;

const gchar COOKIE_JAR_ACCEPT_POLICY_[] = SOUP_COOKIE_JAR_ACCEPT_POLICY;

const gchar COOKIE_JAR_DB_FILENAME_[] = SOUP_COOKIE_JAR_DB_FILENAME;

const gchar COOKIE_JAR_READ_ONLY_[] = SOUP_COOKIE_JAR_READ_ONLY;

const gchar COOKIE_JAR_TEXT_FILENAME_[] = SOUP_COOKIE_JAR_TEXT_FILENAME;

const gint COOKIE_MAX_AGE_ONE_DAY_ = SOUP_COOKIE_MAX_AGE_ONE_DAY;

const gint COOKIE_MAX_AGE_ONE_HOUR_ = SOUP_COOKIE_MAX_AGE_ONE_HOUR;

const gint COOKIE_MAX_AGE_ONE_WEEK_ = SOUP_COOKIE_MAX_AGE_ONE_WEEK;

const gint COOKIE_MAX_AGE_ONE_YEAR_ = SOUP_COOKIE_MAX_AGE_ONE_YEAR;

const gchar FORM_MIME_TYPE_MULTIPART_[] = SOUP_FORM_MIME_TYPE_MULTIPART;

const gchar FORM_MIME_TYPE_URLENCODED_[] = SOUP_FORM_MIME_TYPE_URLENCODED;

const gchar HSTS_ENFORCER_DB_FILENAME_[] = SOUP_HSTS_ENFORCER_DB_FILENAME;

const gint HSTS_POLICY_MAX_AGE_PAST_ = SOUP_HSTS_POLICY_MAX_AGE_PAST;

const gchar LOGGER_LEVEL_[] = SOUP_LOGGER_LEVEL;

const gchar LOGGER_MAX_BODY_SIZE_[] = SOUP_LOGGER_MAX_BODY_SIZE;

const gint MAJOR_VERSION_ = SOUP_MAJOR_VERSION;

const gchar MESSAGE_FIRST_PARTY_[] = SOUP_MESSAGE_FIRST_PARTY;

const gchar MESSAGE_FLAGS_[] = SOUP_MESSAGE_FLAGS;

const gchar MESSAGE_HTTP_VERSION_[] = SOUP_MESSAGE_HTTP_VERSION;

const gchar MESSAGE_IS_TOP_LEVEL_NAVIGATION_[] = SOUP_MESSAGE_IS_TOP_LEVEL_NAVIGATION;

const gchar MESSAGE_METHOD_[] = SOUP_MESSAGE_METHOD;

const gchar MESSAGE_PRIORITY_[] = SOUP_MESSAGE_PRIORITY;

const gchar MESSAGE_REASON_PHRASE_[] = SOUP_MESSAGE_REASON_PHRASE;

const gchar MESSAGE_REQUEST_BODY_[] = SOUP_MESSAGE_REQUEST_BODY;

const gchar MESSAGE_REQUEST_BODY_DATA_[] = SOUP_MESSAGE_REQUEST_BODY_DATA;

const gchar MESSAGE_REQUEST_HEADERS_[] = SOUP_MESSAGE_REQUEST_HEADERS;

const gchar MESSAGE_RESPONSE_BODY_[] = SOUP_MESSAGE_RESPONSE_BODY;

const gchar MESSAGE_RESPONSE_BODY_DATA_[] = SOUP_MESSAGE_RESPONSE_BODY_DATA;

const gchar MESSAGE_RESPONSE_HEADERS_[] = SOUP_MESSAGE_RESPONSE_HEADERS;

const gchar MESSAGE_SERVER_SIDE_[] = SOUP_MESSAGE_SERVER_SIDE;

const gchar MESSAGE_SITE_FOR_COOKIES_[] = SOUP_MESSAGE_SITE_FOR_COOKIES;

const gchar MESSAGE_STATUS_CODE_[] = SOUP_MESSAGE_STATUS_CODE;

const gchar MESSAGE_TLS_CERTIFICATE_[] = SOUP_MESSAGE_TLS_CERTIFICATE;

const gchar MESSAGE_TLS_ERRORS_[] = SOUP_MESSAGE_TLS_ERRORS;

const gchar MESSAGE_URI_[] = SOUP_MESSAGE_URI;

const gint MICRO_VERSION_ = SOUP_MICRO_VERSION;

const gint MINOR_VERSION_ = SOUP_MINOR_VERSION;

const gchar REQUEST_SESSION_[] = SOUP_REQUEST_SESSION;

const gchar REQUEST_URI_[] = SOUP_REQUEST_URI;

const gchar SERVER_ADD_WEBSOCKET_EXTENSION_[] = SOUP_SERVER_ADD_WEBSOCKET_EXTENSION;

const gchar SERVER_HTTPS_ALIASES_[] = SOUP_SERVER_HTTPS_ALIASES;

const gchar SERVER_HTTP_ALIASES_[] = SOUP_SERVER_HTTP_ALIASES;

const gchar SERVER_RAW_PATHS_[] = SOUP_SERVER_RAW_PATHS;

const gchar SERVER_REMOVE_WEBSOCKET_EXTENSION_[] = SOUP_SERVER_REMOVE_WEBSOCKET_EXTENSION;

const gchar SERVER_SERVER_HEADER_[] = SOUP_SERVER_SERVER_HEADER;

const gchar SERVER_TLS_CERTIFICATE_[] = SOUP_SERVER_TLS_CERTIFICATE;

const gchar SESSION_ACCEPT_LANGUAGE_[] = SOUP_SESSION_ACCEPT_LANGUAGE;

const gchar SESSION_ACCEPT_LANGUAGE_AUTO_[] = SOUP_SESSION_ACCEPT_LANGUAGE_AUTO;

const gchar SESSION_ADD_FEATURE_[] = SOUP_SESSION_ADD_FEATURE;

const gchar SESSION_ADD_FEATURE_BY_TYPE_[] = SOUP_SESSION_ADD_FEATURE_BY_TYPE;

const gchar SESSION_ASYNC_CONTEXT_[] = SOUP_SESSION_ASYNC_CONTEXT;

const gchar SESSION_HTTPS_ALIASES_[] = SOUP_SESSION_HTTPS_ALIASES;

const gchar SESSION_HTTP_ALIASES_[] = SOUP_SESSION_HTTP_ALIASES;

const gchar SESSION_IDLE_TIMEOUT_[] = SOUP_SESSION_IDLE_TIMEOUT;

const gchar SESSION_LOCAL_ADDRESS_[] = SOUP_SESSION_LOCAL_ADDRESS;

const gchar SESSION_MAX_CONNS_[] = SOUP_SESSION_MAX_CONNS;

const gchar SESSION_MAX_CONNS_PER_HOST_[] = SOUP_SESSION_MAX_CONNS_PER_HOST;

const gchar SESSION_PROXY_RESOLVER_[] = SOUP_SESSION_PROXY_RESOLVER;

const gchar SESSION_PROXY_URI_[] = SOUP_SESSION_PROXY_URI;

const gchar SESSION_REMOVE_FEATURE_BY_TYPE_[] = SOUP_SESSION_REMOVE_FEATURE_BY_TYPE;

const gchar SESSION_SSL_CA_FILE_[] = SOUP_SESSION_SSL_CA_FILE;

const gchar SESSION_SSL_STRICT_[] = SOUP_SESSION_SSL_STRICT;

const gchar SESSION_SSL_USE_SYSTEM_CA_FILE_[] = SOUP_SESSION_SSL_USE_SYSTEM_CA_FILE;

const gchar SESSION_TIMEOUT_[] = SOUP_SESSION_TIMEOUT;

const gchar SESSION_TLS_DATABASE_[] = SOUP_SESSION_TLS_DATABASE;

const gchar SESSION_TLS_INTERACTION_[] = SOUP_SESSION_TLS_INTERACTION;

const gchar SESSION_USER_AGENT_[] = SOUP_SESSION_USER_AGENT;

const gchar SESSION_USE_NTLM_[] = SOUP_SESSION_USE_NTLM;

const gchar SESSION_USE_THREAD_CONTEXT_[] = SOUP_SESSION_USE_THREAD_CONTEXT;

const gchar SOCKET_ASYNC_CONTEXT_[] = SOUP_SOCKET_ASYNC_CONTEXT;

const gchar SOCKET_FLAG_NONBLOCKING_[] = SOUP_SOCKET_FLAG_NONBLOCKING;

const gchar SOCKET_IS_SERVER_[] = SOUP_SOCKET_IS_SERVER;

const gchar SOCKET_LOCAL_ADDRESS_[] = SOUP_SOCKET_LOCAL_ADDRESS;

const gchar SOCKET_REMOTE_ADDRESS_[] = SOUP_SOCKET_REMOTE_ADDRESS;

const gchar SOCKET_SSL_CREDENTIALS_[] = SOUP_SOCKET_SSL_CREDENTIALS;

const gchar SOCKET_SSL_FALLBACK_[] = SOUP_SOCKET_SSL_FALLBACK;

const gchar SOCKET_SSL_STRICT_[] = SOUP_SOCKET_SSL_STRICT;

const gchar SOCKET_TIMEOUT_[] = SOUP_SOCKET_TIMEOUT;

const gchar SOCKET_TLS_CERTIFICATE_[] = SOUP_SOCKET_TLS_CERTIFICATE;

const gchar SOCKET_TLS_ERRORS_[] = SOUP_SOCKET_TLS_ERRORS;

const gchar SOCKET_TRUSTED_CERTIFICATE_[] = SOUP_SOCKET_TRUSTED_CERTIFICATE;

const gchar SOCKET_USE_THREAD_CONTEXT_[] = SOUP_SOCKET_USE_THREAD_CONTEXT;

const gint VERSION_MIN_REQUIRED_ = SOUP_VERSION_MIN_REQUIRED;

} // namespace Soup

} // namespace repository

} // namespace gi

#endif
