// AUTO-GENERATED

#ifndef _GI_GTK__CONSTANTS_HPP_
#define _GI_GTK__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace Gtk {

const gint BINARY_AGE_ = GTK_BINARY_AGE;

const gint INPUT_ERROR_ = GTK_INPUT_ERROR;

const gint INTERFACE_AGE_ = GTK_INTERFACE_AGE;

const gchar LEVEL_BAR_OFFSET_FULL_[] = GTK_LEVEL_BAR_OFFSET_FULL;

const gchar LEVEL_BAR_OFFSET_HIGH_[] = GTK_LEVEL_BAR_OFFSET_HIGH;

const gchar LEVEL_BAR_OFFSET_LOW_[] = GTK_LEVEL_BAR_OFFSET_LOW;

const gint MAJOR_VERSION_ = GTK_MAJOR_VERSION;

const gint MAX_COMPOSE_LEN_ = GTK_MAX_COMPOSE_LEN;

const gint MICRO_VERSION_ = GTK_MICRO_VERSION;

const gint MINOR_VERSION_ = GTK_MINOR_VERSION;

const gchar PAPER_NAME_A3_[] = GTK_PAPER_NAME_A3;

const gchar PAPER_NAME_A4_[] = GTK_PAPER_NAME_A4;

const gchar PAPER_NAME_A5_[] = GTK_PAPER_NAME_A5;

const gchar PAPER_NAME_B5_[] = GTK_PAPER_NAME_B5;

const gchar PAPER_NAME_EXECUTIVE_[] = GTK_PAPER_NAME_EXECUTIVE;

const gchar PAPER_NAME_LEGAL_[] = GTK_PAPER_NAME_LEGAL;

const gchar PAPER_NAME_LETTER_[] = GTK_PAPER_NAME_LETTER;

const gint PATH_PRIO_MASK_ = GTK_PATH_PRIO_MASK;

const gchar PRINT_SETTINGS_COLLATE_[] = GTK_PRINT_SETTINGS_COLLATE;

const gchar PRINT_SETTINGS_DEFAULT_SOURCE_[] = GTK_PRINT_SETTINGS_DEFAULT_SOURCE;

const gchar PRINT_SETTINGS_DITHER_[] = GTK_PRINT_SETTINGS_DITHER;

const gchar PRINT_SETTINGS_DUPLEX_[] = GTK_PRINT_SETTINGS_DUPLEX;

const gchar PRINT_SETTINGS_FINISHINGS_[] = GTK_PRINT_SETTINGS_FINISHINGS;

const gchar PRINT_SETTINGS_MEDIA_TYPE_[] = GTK_PRINT_SETTINGS_MEDIA_TYPE;

const gchar PRINT_SETTINGS_NUMBER_UP_[] = GTK_PRINT_SETTINGS_NUMBER_UP;

const gchar PRINT_SETTINGS_NUMBER_UP_LAYOUT_[] = GTK_PRINT_SETTINGS_NUMBER_UP_LAYOUT;

const gchar PRINT_SETTINGS_N_COPIES_[] = GTK_PRINT_SETTINGS_N_COPIES;

const gchar PRINT_SETTINGS_ORIENTATION_[] = GTK_PRINT_SETTINGS_ORIENTATION;

const gchar PRINT_SETTINGS_OUTPUT_BASENAME_[] = GTK_PRINT_SETTINGS_OUTPUT_BASENAME;

const gchar PRINT_SETTINGS_OUTPUT_BIN_[] = GTK_PRINT_SETTINGS_OUTPUT_BIN;

const gchar PRINT_SETTINGS_OUTPUT_DIR_[] = GTK_PRINT_SETTINGS_OUTPUT_DIR;

const gchar PRINT_SETTINGS_OUTPUT_FILE_FORMAT_[] = GTK_PRINT_SETTINGS_OUTPUT_FILE_FORMAT;

const gchar PRINT_SETTINGS_OUTPUT_URI_[] = GTK_PRINT_SETTINGS_OUTPUT_URI;

const gchar PRINT_SETTINGS_PAGE_RANGES_[] = GTK_PRINT_SETTINGS_PAGE_RANGES;

const gchar PRINT_SETTINGS_PAGE_SET_[] = GTK_PRINT_SETTINGS_PAGE_SET;

const gchar PRINT_SETTINGS_PAPER_FORMAT_[] = GTK_PRINT_SETTINGS_PAPER_FORMAT;

const gchar PRINT_SETTINGS_PAPER_HEIGHT_[] = GTK_PRINT_SETTINGS_PAPER_HEIGHT;

const gchar PRINT_SETTINGS_PAPER_WIDTH_[] = GTK_PRINT_SETTINGS_PAPER_WIDTH;

const gchar PRINT_SETTINGS_PRINTER_[] = GTK_PRINT_SETTINGS_PRINTER;

const gchar PRINT_SETTINGS_PRINTER_LPI_[] = GTK_PRINT_SETTINGS_PRINTER_LPI;

const gchar PRINT_SETTINGS_PRINT_PAGES_[] = GTK_PRINT_SETTINGS_PRINT_PAGES;

const gchar PRINT_SETTINGS_QUALITY_[] = GTK_PRINT_SETTINGS_QUALITY;

const gchar PRINT_SETTINGS_RESOLUTION_[] = GTK_PRINT_SETTINGS_RESOLUTION;

const gchar PRINT_SETTINGS_RESOLUTION_X_[] = GTK_PRINT_SETTINGS_RESOLUTION_X;

const gchar PRINT_SETTINGS_RESOLUTION_Y_[] = GTK_PRINT_SETTINGS_RESOLUTION_Y;

const gchar PRINT_SETTINGS_REVERSE_[] = GTK_PRINT_SETTINGS_REVERSE;

const gchar PRINT_SETTINGS_SCALE_[] = GTK_PRINT_SETTINGS_SCALE;

const gchar PRINT_SETTINGS_USE_COLOR_[] = GTK_PRINT_SETTINGS_USE_COLOR;

const gchar PRINT_SETTINGS_WIN32_DRIVER_EXTRA_[] = GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA;

const gchar PRINT_SETTINGS_WIN32_DRIVER_VERSION_[] = GTK_PRINT_SETTINGS_WIN32_DRIVER_VERSION;

const gint PRIORITY_RESIZE_ = GTK_PRIORITY_RESIZE;

const gchar STYLE_CLASS_ACCELERATOR_[] = GTK_STYLE_CLASS_ACCELERATOR;

const gchar STYLE_CLASS_ARROW_[] = GTK_STYLE_CLASS_ARROW;

const gchar STYLE_CLASS_BACKGROUND_[] = GTK_STYLE_CLASS_BACKGROUND;

const gchar STYLE_CLASS_BOTTOM_[] = GTK_STYLE_CLASS_BOTTOM;

const gchar STYLE_CLASS_BUTTON_[] = GTK_STYLE_CLASS_BUTTON;

const gchar STYLE_CLASS_CALENDAR_[] = GTK_STYLE_CLASS_CALENDAR;

const gchar STYLE_CLASS_CELL_[] = GTK_STYLE_CLASS_CELL;

const gchar STYLE_CLASS_CHECK_[] = GTK_STYLE_CLASS_CHECK;

const gchar STYLE_CLASS_COMBOBOX_ENTRY_[] = GTK_STYLE_CLASS_COMBOBOX_ENTRY;

const gchar STYLE_CLASS_CONTEXT_MENU_[] = GTK_STYLE_CLASS_CONTEXT_MENU;

const gchar STYLE_CLASS_CSD_[] = GTK_STYLE_CLASS_CSD;

const gchar STYLE_CLASS_CURSOR_HANDLE_[] = GTK_STYLE_CLASS_CURSOR_HANDLE;

const gchar STYLE_CLASS_DEFAULT_[] = GTK_STYLE_CLASS_DEFAULT;

const gchar STYLE_CLASS_DESTRUCTIVE_ACTION_[] = GTK_STYLE_CLASS_DESTRUCTIVE_ACTION;

const gchar STYLE_CLASS_DIM_LABEL_[] = GTK_STYLE_CLASS_DIM_LABEL;

const gchar STYLE_CLASS_DND_[] = GTK_STYLE_CLASS_DND;

const gchar STYLE_CLASS_DOCK_[] = GTK_STYLE_CLASS_DOCK;

const gchar STYLE_CLASS_ENTRY_[] = GTK_STYLE_CLASS_ENTRY;

const gchar STYLE_CLASS_ERROR_[] = GTK_STYLE_CLASS_ERROR;

const gchar STYLE_CLASS_EXPANDER_[] = GTK_STYLE_CLASS_EXPANDER;

const gchar STYLE_CLASS_FLAT_[] = GTK_STYLE_CLASS_FLAT;

const gchar STYLE_CLASS_FRAME_[] = GTK_STYLE_CLASS_FRAME;

const gchar STYLE_CLASS_GRIP_[] = GTK_STYLE_CLASS_GRIP;

const gchar STYLE_CLASS_HEADER_[] = GTK_STYLE_CLASS_HEADER;

const gchar STYLE_CLASS_HIGHLIGHT_[] = GTK_STYLE_CLASS_HIGHLIGHT;

const gchar STYLE_CLASS_HORIZONTAL_[] = GTK_STYLE_CLASS_HORIZONTAL;

const gchar STYLE_CLASS_IMAGE_[] = GTK_STYLE_CLASS_IMAGE;

const gchar STYLE_CLASS_INFO_[] = GTK_STYLE_CLASS_INFO;

const gchar STYLE_CLASS_INLINE_TOOLBAR_[] = GTK_STYLE_CLASS_INLINE_TOOLBAR;

const gchar STYLE_CLASS_INSERTION_CURSOR_[] = GTK_STYLE_CLASS_INSERTION_CURSOR;

const gchar STYLE_CLASS_LABEL_[] = GTK_STYLE_CLASS_LABEL;

const gchar STYLE_CLASS_LEFT_[] = GTK_STYLE_CLASS_LEFT;

const gchar STYLE_CLASS_LEVEL_BAR_[] = GTK_STYLE_CLASS_LEVEL_BAR;

const gchar STYLE_CLASS_LINKED_[] = GTK_STYLE_CLASS_LINKED;

const gchar STYLE_CLASS_LIST_[] = GTK_STYLE_CLASS_LIST;

const gchar STYLE_CLASS_LIST_ROW_[] = GTK_STYLE_CLASS_LIST_ROW;

const gchar STYLE_CLASS_MARK_[] = GTK_STYLE_CLASS_MARK;

const gchar STYLE_CLASS_MENU_[] = GTK_STYLE_CLASS_MENU;

const gchar STYLE_CLASS_MENUBAR_[] = GTK_STYLE_CLASS_MENUBAR;

const gchar STYLE_CLASS_MENUITEM_[] = GTK_STYLE_CLASS_MENUITEM;

const gchar STYLE_CLASS_MESSAGE_DIALOG_[] = GTK_STYLE_CLASS_MESSAGE_DIALOG;

const gchar STYLE_CLASS_MONOSPACE_[] = GTK_STYLE_CLASS_MONOSPACE;

const gchar STYLE_CLASS_NEEDS_ATTENTION_[] = GTK_STYLE_CLASS_NEEDS_ATTENTION;

const gchar STYLE_CLASS_NOTEBOOK_[] = GTK_STYLE_CLASS_NOTEBOOK;

const gchar STYLE_CLASS_OSD_[] = GTK_STYLE_CLASS_OSD;

const gchar STYLE_CLASS_OVERSHOOT_[] = GTK_STYLE_CLASS_OVERSHOOT;

const gchar STYLE_CLASS_PANE_SEPARATOR_[] = GTK_STYLE_CLASS_PANE_SEPARATOR;

const gchar STYLE_CLASS_PAPER_[] = GTK_STYLE_CLASS_PAPER;

const gchar STYLE_CLASS_POPOVER_[] = GTK_STYLE_CLASS_POPOVER;

const gchar STYLE_CLASS_POPUP_[] = GTK_STYLE_CLASS_POPUP;

const gchar STYLE_CLASS_PRIMARY_TOOLBAR_[] = GTK_STYLE_CLASS_PRIMARY_TOOLBAR;

const gchar STYLE_CLASS_PROGRESSBAR_[] = GTK_STYLE_CLASS_PROGRESSBAR;

const gchar STYLE_CLASS_PULSE_[] = GTK_STYLE_CLASS_PULSE;

const gchar STYLE_CLASS_QUESTION_[] = GTK_STYLE_CLASS_QUESTION;

const gchar STYLE_CLASS_RADIO_[] = GTK_STYLE_CLASS_RADIO;

const gchar STYLE_CLASS_RAISED_[] = GTK_STYLE_CLASS_RAISED;

const gchar STYLE_CLASS_READ_ONLY_[] = GTK_STYLE_CLASS_READ_ONLY;

const gchar STYLE_CLASS_RIGHT_[] = GTK_STYLE_CLASS_RIGHT;

const gchar STYLE_CLASS_RUBBERBAND_[] = GTK_STYLE_CLASS_RUBBERBAND;

const gchar STYLE_CLASS_SCALE_[] = GTK_STYLE_CLASS_SCALE;

const gchar STYLE_CLASS_SCALE_HAS_MARKS_ABOVE_[] = GTK_STYLE_CLASS_SCALE_HAS_MARKS_ABOVE;

const gchar STYLE_CLASS_SCALE_HAS_MARKS_BELOW_[] = GTK_STYLE_CLASS_SCALE_HAS_MARKS_BELOW;

const gchar STYLE_CLASS_SCROLLBAR_[] = GTK_STYLE_CLASS_SCROLLBAR;

const gchar STYLE_CLASS_SCROLLBARS_JUNCTION_[] = GTK_STYLE_CLASS_SCROLLBARS_JUNCTION;

const gchar STYLE_CLASS_SEPARATOR_[] = GTK_STYLE_CLASS_SEPARATOR;

const gchar STYLE_CLASS_SIDEBAR_[] = GTK_STYLE_CLASS_SIDEBAR;

const gchar STYLE_CLASS_SLIDER_[] = GTK_STYLE_CLASS_SLIDER;

const gchar STYLE_CLASS_SPINBUTTON_[] = GTK_STYLE_CLASS_SPINBUTTON;

const gchar STYLE_CLASS_SPINNER_[] = GTK_STYLE_CLASS_SPINNER;

const gchar STYLE_CLASS_STATUSBAR_[] = GTK_STYLE_CLASS_STATUSBAR;

const gchar STYLE_CLASS_SUBTITLE_[] = GTK_STYLE_CLASS_SUBTITLE;

const gchar STYLE_CLASS_SUGGESTED_ACTION_[] = GTK_STYLE_CLASS_SUGGESTED_ACTION;

const gchar STYLE_CLASS_TITLE_[] = GTK_STYLE_CLASS_TITLE;

const gchar STYLE_CLASS_TITLEBAR_[] = GTK_STYLE_CLASS_TITLEBAR;

const gchar STYLE_CLASS_TOOLBAR_[] = GTK_STYLE_CLASS_TOOLBAR;

const gchar STYLE_CLASS_TOOLTIP_[] = GTK_STYLE_CLASS_TOOLTIP;

const gchar STYLE_CLASS_TOP_[] = GTK_STYLE_CLASS_TOP;

const gchar STYLE_CLASS_TOUCH_SELECTION_[] = GTK_STYLE_CLASS_TOUCH_SELECTION;

const gchar STYLE_CLASS_TROUGH_[] = GTK_STYLE_CLASS_TROUGH;

const gchar STYLE_CLASS_UNDERSHOOT_[] = GTK_STYLE_CLASS_UNDERSHOOT;

const gchar STYLE_CLASS_VERTICAL_[] = GTK_STYLE_CLASS_VERTICAL;

const gchar STYLE_CLASS_VIEW_[] = GTK_STYLE_CLASS_VIEW;

const gchar STYLE_CLASS_WARNING_[] = GTK_STYLE_CLASS_WARNING;

const gchar STYLE_CLASS_WIDE_[] = GTK_STYLE_CLASS_WIDE;

const gchar STYLE_PROPERTY_BACKGROUND_COLOR_[] = GTK_STYLE_PROPERTY_BACKGROUND_COLOR;

const gchar STYLE_PROPERTY_BACKGROUND_IMAGE_[] = GTK_STYLE_PROPERTY_BACKGROUND_IMAGE;

const gchar STYLE_PROPERTY_BORDER_COLOR_[] = GTK_STYLE_PROPERTY_BORDER_COLOR;

const gchar STYLE_PROPERTY_BORDER_RADIUS_[] = GTK_STYLE_PROPERTY_BORDER_RADIUS;

const gchar STYLE_PROPERTY_BORDER_STYLE_[] = GTK_STYLE_PROPERTY_BORDER_STYLE;

const gchar STYLE_PROPERTY_BORDER_WIDTH_[] = GTK_STYLE_PROPERTY_BORDER_WIDTH;

const gchar STYLE_PROPERTY_COLOR_[] = GTK_STYLE_PROPERTY_COLOR;

const gchar STYLE_PROPERTY_FONT_[] = GTK_STYLE_PROPERTY_FONT;

const gchar STYLE_PROPERTY_MARGIN_[] = GTK_STYLE_PROPERTY_MARGIN;

const gchar STYLE_PROPERTY_PADDING_[] = GTK_STYLE_PROPERTY_PADDING;

const gint STYLE_PROVIDER_PRIORITY_APPLICATION_ = GTK_STYLE_PROVIDER_PRIORITY_APPLICATION;

const gint STYLE_PROVIDER_PRIORITY_FALLBACK_ = GTK_STYLE_PROVIDER_PRIORITY_FALLBACK;

const gint STYLE_PROVIDER_PRIORITY_SETTINGS_ = GTK_STYLE_PROVIDER_PRIORITY_SETTINGS;

const gint STYLE_PROVIDER_PRIORITY_THEME_ = GTK_STYLE_PROVIDER_PRIORITY_THEME;

const gint STYLE_PROVIDER_PRIORITY_USER_ = GTK_STYLE_PROVIDER_PRIORITY_USER;

const gint TEXT_VIEW_PRIORITY_VALIDATE_ = GTK_TEXT_VIEW_PRIORITY_VALIDATE;

const gint TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID_ = GTK_TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID;

const gint TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID_ = GTK_TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID;

} // namespace Gtk

} // namespace repository

} // namespace gi

#endif
