// AUTO-GENERATED

#ifndef _GI_GTK_GTK_HPP_
#define _GI_GTK_GTK_HPP_

#include <gi/gi.hpp>

#include <atk/atk.hpp>
#include <gdk/gdk.hpp>
#include <xlib/xlib.hpp>


#if defined(__has_include)
#if __has_include(<gtk/gtk_setup_pre_def.hpp>)
#include <gtk/gtk_setup_pre_def.hpp>
#endif
#endif


#if defined(__has_include)
#if __has_include(<gtk/gtk_setup_pre.hpp>)
#include <gtk/gtk_setup_pre.hpp>
#endif
#endif

#include <gtk/gtk-a11y.h>
#include <gtk/gtk.h>
#include <gtk/gtkx.h>

#if defined(__has_include)
#if __has_include(<gtk/gtk_setup_post_def.hpp>)
#include <gtk/gtk_setup_post_def.hpp>
#endif
#endif


#if defined(__has_include)
#if __has_include(<gtk/gtk_setup_post.hpp>)
#include <gtk/gtk_setup_post.hpp>
#endif
#endif


GI_DISABLE_DEPRECATED_WARN_BEGIN

#include "_types.hpp"
#include "_enums.hpp"
#include "_flags.hpp"
#include "_constants.hpp"
#include "_callbacks.hpp"


#include "aboutdialog.hpp"
#include "accelgroup.hpp"
#include "accelgroupentry.hpp"
#include "accelkey.hpp"
#include "accellabel.hpp"
#include "accelmap.hpp"
#include "accessible.hpp"
#include "action.hpp"
#include "actionable.hpp"
#include "actionbar.hpp"
#include "actiongroup.hpp"
#include "activatable.hpp"
#include "adjustment.hpp"
#include "alignment.hpp"
#include "appchooser.hpp"
#include "appchooserbutton.hpp"
#include "appchooserdialog.hpp"
#include "appchooserwidget.hpp"
#include "application.hpp"
#include "applicationwindow.hpp"
#include "arrow.hpp"
#include "arrowaccessible.hpp"
#include "aspectframe.hpp"
#include "assistant.hpp"
#include "bin.hpp"
#include "bindingarg.hpp"
#include "bindingentry.hpp"
#include "bindingset.hpp"
#include "bindingsignal.hpp"
#include "booleancellaccessible.hpp"
#include "border.hpp"
#include "box.hpp"
#include "buildable.hpp"
#include "builder.hpp"
#include "button.hpp"
#include "buttonaccessible.hpp"
#include "buttonbox.hpp"
#include "calendar.hpp"
#include "cellaccessible.hpp"
#include "cellaccessibleparent.hpp"
#include "cellarea.hpp"
#include "cellareabox.hpp"
#include "cellareacontext.hpp"
#include "celleditable.hpp"
#include "celllayout.hpp"
#include "cellrenderer.hpp"
#include "cellrendereraccel.hpp"
#include "cellrenderercombo.hpp"
#include "cellrendererpixbuf.hpp"
#include "cellrendererprogress.hpp"
#include "cellrendererspin.hpp"
#include "cellrendererspinner.hpp"
#include "cellrenderertext.hpp"
#include "cellrenderertoggle.hpp"
#include "cellview.hpp"
#include "checkbutton.hpp"
#include "checkmenuitem.hpp"
#include "checkmenuitemaccessible.hpp"
#include "clipboard.hpp"
#include "colorbutton.hpp"
#include "colorchooser.hpp"
#include "colorchooserdialog.hpp"
#include "colorchooserwidget.hpp"
#include "colorselection.hpp"
#include "colorselectiondialog.hpp"
#include "combobox.hpp"
#include "comboboxaccessible.hpp"
#include "comboboxtext.hpp"
#include "container.hpp"
#include "containeraccessible.hpp"
#include "containercellaccessible.hpp"
#include "cssprovider.hpp"
#include "csssection.hpp"
#include "dialog.hpp"
#include "drawingarea.hpp"
#include "editable.hpp"
#include "entry.hpp"
#include "entryaccessible.hpp"
#include "entrybuffer.hpp"
#include "entrycompletion.hpp"
#include "eventbox.hpp"
#include "eventcontroller.hpp"
#include "eventcontrollerkey.hpp"
#include "eventcontrollermotion.hpp"
#include "eventcontrollerscroll.hpp"
#include "expander.hpp"
#include "expanderaccessible.hpp"
#include "filechooser.hpp"
#include "filechooserbutton.hpp"
#include "filechooserdialog.hpp"
#include "filechoosernative.hpp"
#include "filechooserwidget.hpp"
#include "filechooserwidgetaccessible.hpp"
#include "filefilter.hpp"
#include "filefilterinfo.hpp"
#include "fixed.hpp"
#include "fixedchild.hpp"
#include "flowbox.hpp"
#include "flowboxaccessible.hpp"
#include "flowboxchild.hpp"
#include "flowboxchildaccessible.hpp"
#include "fontbutton.hpp"
#include "fontchooser.hpp"
#include "fontchooserdialog.hpp"
#include "fontchooserwidget.hpp"
#include "fontselection.hpp"
#include "fontselectiondialog.hpp"
#include "frame.hpp"
#include "frameaccessible.hpp"
#include "gesture.hpp"
#include "gesturedrag.hpp"
#include "gesturelongpress.hpp"
#include "gesturemultipress.hpp"
#include "gesturepan.hpp"
#include "gesturerotate.hpp"
#include "gesturesingle.hpp"
#include "gesturestylus.hpp"
#include "gestureswipe.hpp"
#include "gesturezoom.hpp"
#include "glarea.hpp"
#include "gradient.hpp"
#include "grid.hpp"
#include "handlebox.hpp"
#include "hbox.hpp"
#include "hbuttonbox.hpp"
#include "headerbar.hpp"
#include "hpaned.hpp"
#include "hscale.hpp"
#include "hscrollbar.hpp"
#include "hseparator.hpp"
#include "hsv.hpp"
#include "iconfactory.hpp"
#include "iconinfo.hpp"
#include "iconset.hpp"
#include "iconsource.hpp"
#include "icontheme.hpp"
#include "iconview.hpp"
#include "iconviewaccessible.hpp"
#include "image.hpp"
#include "imageaccessible.hpp"
#include "imagecellaccessible.hpp"
#include "imagemenuitem.hpp"
#include "imcontext.hpp"
#include "imcontextinfo.hpp"
#include "imcontextsimple.hpp"
#include "immulticontext.hpp"
#include "infobar.hpp"
#include "invisible.hpp"
#include "label.hpp"
#include "labelaccessible.hpp"
#include "layout.hpp"
#include "levelbar.hpp"
#include "levelbaraccessible.hpp"
#include "linkbutton.hpp"
#include "linkbuttonaccessible.hpp"
#include "listbox.hpp"
#include "listboxaccessible.hpp"
#include "listboxrow.hpp"
#include "listboxrowaccessible.hpp"
#include "liststore.hpp"
#include "lockbutton.hpp"
#include "lockbuttonaccessible.hpp"
#include "menu.hpp"
#include "menuaccessible.hpp"
#include "menubar.hpp"
#include "menubutton.hpp"
#include "menubuttonaccessible.hpp"
#include "menuitem.hpp"
#include "menuitemaccessible.hpp"
#include "menushell.hpp"
#include "menushellaccessible.hpp"
#include "menutoolbutton.hpp"
#include "messagedialog.hpp"
#include "misc.hpp"
#include "modelbutton.hpp"
#include "mountoperation.hpp"
#include "nativedialog.hpp"
#include "notebook.hpp"
#include "notebookaccessible.hpp"
#include "notebookpageaccessible.hpp"
#include "numerableicon.hpp"
#include "offscreenwindow.hpp"
#include "orientable.hpp"
#include "overlay.hpp"
#include "padactionentry.hpp"
#include "padcontroller.hpp"
#include "pagerange.hpp"
#include "pagesetup.hpp"
#include "paned.hpp"
#include "panedaccessible.hpp"
#include "papersize.hpp"
#include "placessidebar.hpp"
#include "plugaccessible.hpp"
#include "popover.hpp"
#include "popoveraccessible.hpp"
#include "popovermenu.hpp"
#include "printcontext.hpp"
#include "printoperation.hpp"
#include "printoperationpreview.hpp"
#include "printsettings.hpp"
#include "progressbar.hpp"
#include "progressbaraccessible.hpp"
#include "radioaction.hpp"
#include "radiobutton.hpp"
#include "radiobuttonaccessible.hpp"
#include "radiomenuitem.hpp"
#include "radiomenuitemaccessible.hpp"
#include "radiotoolbutton.hpp"
#include "range.hpp"
#include "rangeaccessible.hpp"
#include "rcproperty.hpp"
#include "rcstyle.hpp"
#include "recentaction.hpp"
#include "recentchooser.hpp"
#include "recentchooserdialog.hpp"
#include "recentchoosermenu.hpp"
#include "recentchooserwidget.hpp"
#include "recentdata.hpp"
#include "recentfilter.hpp"
#include "recentfilterinfo.hpp"
#include "recentinfo.hpp"
#include "recentmanager.hpp"
#include "renderercellaccessible.hpp"
#include "requestedsize.hpp"
#include "requisition.hpp"
#include "revealer.hpp"
#include "scale.hpp"
#include "scaleaccessible.hpp"
#include "scalebutton.hpp"
#include "scalebuttonaccessible.hpp"
#include "scrollable.hpp"
#include "scrollbar.hpp"
#include "scrolledwindow.hpp"
#include "scrolledwindowaccessible.hpp"
#include "searchbar.hpp"
#include "searchentry.hpp"
#include "selectiondata.hpp"
#include "separator.hpp"
#include "separatormenuitem.hpp"
#include "separatortoolitem.hpp"
#include "settings.hpp"
#include "settingsvalue.hpp"
#include "shortcutlabel.hpp"
#include "shortcutsgroup.hpp"
#include "shortcutssection.hpp"
#include "shortcutsshortcut.hpp"
#include "shortcutswindow.hpp"
#include "sizegroup.hpp"
#include "socketaccessible.hpp"
#include "spinbutton.hpp"
#include "spinbuttonaccessible.hpp"
#include "spinner.hpp"
#include "spinneraccessible.hpp"
#include "stack.hpp"
#include "stackaccessible.hpp"
#include "stacksidebar.hpp"
#include "stackswitcher.hpp"
#include "statusbar.hpp"
#include "statusbaraccessible.hpp"
#include "statusicon.hpp"
#include "style.hpp"
#include "stylecontext.hpp"
#include "styleproperties.hpp"
#include "styleprovider.hpp"
#include "switch.hpp"
#include "switchaccessible.hpp"
#include "symboliccolor.hpp"
#include "table.hpp"
#include "tablechild.hpp"
#include "tablerowcol.hpp"
#include "targetentry.hpp"
#include "targetlist.hpp"
#include "targetpair.hpp"
#include "tearoffmenuitem.hpp"
#include "textappearance.hpp"
#include "textattributes.hpp"
#include "textbuffer.hpp"
#include "textcellaccessible.hpp"
#include "textchildanchor.hpp"
#include "textiter.hpp"
#include "textmark.hpp"
#include "texttag.hpp"
#include "texttagtable.hpp"
#include "textview.hpp"
#include "textviewaccessible.hpp"
#include "themingengine.hpp"
#include "toggleaction.hpp"
#include "togglebutton.hpp"
#include "togglebuttonaccessible.hpp"
#include "toggletoolbutton.hpp"
#include "toolbar.hpp"
#include "toolbutton.hpp"
#include "toolitem.hpp"
#include "toolitemgroup.hpp"
#include "toolpalette.hpp"
#include "toolshell.hpp"
#include "tooltip.hpp"
#include "toplevelaccessible.hpp"
#include "treedragdest.hpp"
#include "treedragsource.hpp"
#include "treeiter.hpp"
#include "treemodel.hpp"
#include "treemodelfilter.hpp"
#include "treemodelsort.hpp"
#include "treepath.hpp"
#include "treerowreference.hpp"
#include "treeselection.hpp"
#include "treesortable.hpp"
#include "treestore.hpp"
#include "treeview.hpp"
#include "treeviewaccessible.hpp"
#include "treeviewcolumn.hpp"
#include "uimanager.hpp"
#include "vbox.hpp"
#include "vbuttonbox.hpp"
#include "viewport.hpp"
#include "volumebutton.hpp"
#include "vpaned.hpp"
#include "vscale.hpp"
#include "vscrollbar.hpp"
#include "vseparator.hpp"
#include "widget.hpp"
#include "widgetaccessible.hpp"
#include "widgetpath.hpp"
#include "window.hpp"
#include "windowaccessible.hpp"
#include "windowgroup.hpp"

#include "_functions.hpp"


#if defined(__has_include)
#if __has_include(<gtk/gtk_extra_def.hpp>)
#include <gtk/gtk_extra_def.hpp>
#endif
#endif


#if defined(__has_include)
#if __has_include(<gtk/gtk_extra.hpp>)
#include <gtk/gtk_extra.hpp>
#endif
#endif

GI_DISABLE_DEPRECATED_WARN_END

#if defined(GI_INLINE) || defined(GI_INCLUDE_IMPL)
#include "gtk_impl.hpp"
#endif

#endif
