// AUTO-GENERATED

#ifndef _GI_WEBKIT2__CONSTANTS_HPP_
#define _GI_WEBKIT2__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace WebKit2 {

const gchar EDITING_COMMAND_COPY_[] = WEBKIT_EDITING_COMMAND_COPY;

const gchar EDITING_COMMAND_CREATE_LINK_[] = WEBKIT_EDITING_COMMAND_CREATE_LINK;

const gchar EDITING_COMMAND_CUT_[] = WEBKIT_EDITING_COMMAND_CUT;

const gchar EDITING_COMMAND_INSERT_IMAGE_[] = WEBKIT_EDITING_COMMAND_INSERT_IMAGE;

const gchar EDITING_COMMAND_PASTE_[] = WEBKIT_EDITING_COMMAND_PASTE;

const gchar EDITING_COMMAND_PASTE_AS_PLAIN_TEXT_[] = WEBKIT_EDITING_COMMAND_PASTE_AS_PLAIN_TEXT;

const gchar EDITING_COMMAND_REDO_[] = WEBKIT_EDITING_COMMAND_REDO;

const gchar EDITING_COMMAND_SELECT_ALL_[] = WEBKIT_EDITING_COMMAND_SELECT_ALL;

const gchar EDITING_COMMAND_UNDO_[] = WEBKIT_EDITING_COMMAND_UNDO;

const gint MAJOR_VERSION_ = WEBKIT_MAJOR_VERSION;

const gint MICRO_VERSION_ = WEBKIT_MICRO_VERSION;

const gint MINOR_VERSION_ = WEBKIT_MINOR_VERSION;

} // namespace WebKit2

} // namespace repository

} // namespace gi

#endif
