// AUTO-GENERATED

#ifndef _GI_GST__CONSTANTS_HPP_
#define _GI_GST__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace Gst {

const gchar ALLOCATOR_SYSMEM_[] = GST_ALLOCATOR_SYSMEM;

const Gst::BufferCopyFlags BUFFER_COPY_ALL_ = (Gst::BufferCopyFlags) GST_BUFFER_COPY_ALL;

const Gst::BufferCopyFlags BUFFER_COPY_METADATA_ = (Gst::BufferCopyFlags) GST_BUFFER_COPY_METADATA;

const guint64 BUFFER_OFFSET_NONE_ = GST_BUFFER_OFFSET_NONE;

const gint CAN_INLINE_ = GST_CAN_INLINE;

const gchar CAPS_FEATURE_MEMORY_SYSTEM_MEMORY_[] = GST_CAPS_FEATURE_MEMORY_SYSTEM_MEMORY;

const GstClockTime CLOCK_TIME_NONE_ = GST_CLOCK_TIME_NONE;

const gint DEBUG_BG_MASK_ = GST_DEBUG_BG_MASK;

const gint DEBUG_FG_MASK_ = GST_DEBUG_FG_MASK;

const gint DEBUG_FORMAT_MASK_ = GST_DEBUG_FORMAT_MASK;

const gchar ELEMENT_FACTORY_KLASS_DECODER_[] = GST_ELEMENT_FACTORY_KLASS_DECODER;

const gchar ELEMENT_FACTORY_KLASS_DECRYPTOR_[] = GST_ELEMENT_FACTORY_KLASS_DECRYPTOR;

const gchar ELEMENT_FACTORY_KLASS_DEMUXER_[] = GST_ELEMENT_FACTORY_KLASS_DEMUXER;

const gchar ELEMENT_FACTORY_KLASS_DEPAYLOADER_[] = GST_ELEMENT_FACTORY_KLASS_DEPAYLOADER;

const gchar ELEMENT_FACTORY_KLASS_ENCODER_[] = GST_ELEMENT_FACTORY_KLASS_ENCODER;

const gchar ELEMENT_FACTORY_KLASS_ENCRYPTOR_[] = GST_ELEMENT_FACTORY_KLASS_ENCRYPTOR;

const gchar ELEMENT_FACTORY_KLASS_FORMATTER_[] = GST_ELEMENT_FACTORY_KLASS_FORMATTER;

const gchar ELEMENT_FACTORY_KLASS_HARDWARE_[] = GST_ELEMENT_FACTORY_KLASS_HARDWARE;

const gchar ELEMENT_FACTORY_KLASS_MEDIA_AUDIO_[] = GST_ELEMENT_FACTORY_KLASS_MEDIA_AUDIO;

const gchar ELEMENT_FACTORY_KLASS_MEDIA_IMAGE_[] = GST_ELEMENT_FACTORY_KLASS_MEDIA_IMAGE;

const gchar ELEMENT_FACTORY_KLASS_MEDIA_METADATA_[] = GST_ELEMENT_FACTORY_KLASS_MEDIA_METADATA;

const gchar ELEMENT_FACTORY_KLASS_MEDIA_SUBTITLE_[] = GST_ELEMENT_FACTORY_KLASS_MEDIA_SUBTITLE;

const gchar ELEMENT_FACTORY_KLASS_MEDIA_VIDEO_[] = GST_ELEMENT_FACTORY_KLASS_MEDIA_VIDEO;

const gchar ELEMENT_FACTORY_KLASS_MUXER_[] = GST_ELEMENT_FACTORY_KLASS_MUXER;

const gchar ELEMENT_FACTORY_KLASS_PARSER_[] = GST_ELEMENT_FACTORY_KLASS_PARSER;

const gchar ELEMENT_FACTORY_KLASS_PAYLOADER_[] = GST_ELEMENT_FACTORY_KLASS_PAYLOADER;

const gchar ELEMENT_FACTORY_KLASS_SINK_[] = GST_ELEMENT_FACTORY_KLASS_SINK;

const gchar ELEMENT_FACTORY_KLASS_SRC_[] = GST_ELEMENT_FACTORY_KLASS_SRC;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_ANY_ = GST_ELEMENT_FACTORY_TYPE_ANY;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_AUDIOVIDEO_SINKS_ = GST_ELEMENT_FACTORY_TYPE_AUDIOVIDEO_SINKS;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_AUDIO_ENCODER_ = GST_ELEMENT_FACTORY_TYPE_AUDIO_ENCODER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_DECODABLE_ = GST_ELEMENT_FACTORY_TYPE_DECODABLE;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_DECODER_ = GST_ELEMENT_FACTORY_TYPE_DECODER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_DECRYPTOR_ = GST_ELEMENT_FACTORY_TYPE_DECRYPTOR;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_DEMUXER_ = GST_ELEMENT_FACTORY_TYPE_DEMUXER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_DEPAYLOADER_ = GST_ELEMENT_FACTORY_TYPE_DEPAYLOADER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_ENCODER_ = GST_ELEMENT_FACTORY_TYPE_ENCODER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_ENCRYPTOR_ = GST_ELEMENT_FACTORY_TYPE_ENCRYPTOR;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_FORMATTER_ = GST_ELEMENT_FACTORY_TYPE_FORMATTER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_HARDWARE_ = GST_ELEMENT_FACTORY_TYPE_HARDWARE;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_MAX_ELEMENTS_ = GST_ELEMENT_FACTORY_TYPE_MAX_ELEMENTS;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_MEDIA_ANY_ = GST_ELEMENT_FACTORY_TYPE_MEDIA_ANY;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_MEDIA_AUDIO_ = GST_ELEMENT_FACTORY_TYPE_MEDIA_AUDIO;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_MEDIA_IMAGE_ = GST_ELEMENT_FACTORY_TYPE_MEDIA_IMAGE;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_MEDIA_METADATA_ = GST_ELEMENT_FACTORY_TYPE_MEDIA_METADATA;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_MEDIA_SUBTITLE_ = GST_ELEMENT_FACTORY_TYPE_MEDIA_SUBTITLE;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_MEDIA_VIDEO_ = GST_ELEMENT_FACTORY_TYPE_MEDIA_VIDEO;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_MUXER_ = GST_ELEMENT_FACTORY_TYPE_MUXER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_PARSER_ = GST_ELEMENT_FACTORY_TYPE_PARSER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_PAYLOADER_ = GST_ELEMENT_FACTORY_TYPE_PAYLOADER;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_SINK_ = GST_ELEMENT_FACTORY_TYPE_SINK;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_SRC_ = GST_ELEMENT_FACTORY_TYPE_SRC;

const GstElementFactoryListType ELEMENT_FACTORY_TYPE_VIDEO_ENCODER_ = GST_ELEMENT_FACTORY_TYPE_VIDEO_ENCODER;

const gchar ELEMENT_METADATA_AUTHOR_[] = GST_ELEMENT_METADATA_AUTHOR;

const gchar ELEMENT_METADATA_DESCRIPTION_[] = GST_ELEMENT_METADATA_DESCRIPTION;

const gchar ELEMENT_METADATA_DOC_URI_[] = GST_ELEMENT_METADATA_DOC_URI;

const gchar ELEMENT_METADATA_ICON_NAME_[] = GST_ELEMENT_METADATA_ICON_NAME;

const gchar ELEMENT_METADATA_KLASS_[] = GST_ELEMENT_METADATA_KLASS;

const gchar ELEMENT_METADATA_LONGNAME_[] = GST_ELEMENT_METADATA_LONGNAME;

const gint EVENT_NUM_SHIFT_ = GST_EVENT_NUM_SHIFT;

const Gst::EventTypeFlags EVENT_TYPE_BOTH_ = (Gst::EventTypeFlags) GST_EVENT_TYPE_BOTH;

const guint FLAG_SET_MASK_EXACT_ = GST_FLAG_SET_MASK_EXACT;

const gint64 FORMAT_PERCENT_MAX_ = GST_FORMAT_PERCENT_MAX;

const gint64 FORMAT_PERCENT_SCALE_ = GST_FORMAT_PERCENT_SCALE;

const gchar FOURCC_FORMAT_[] = GST_FOURCC_FORMAT;

const gint GROUP_ID_INVALID_ = GST_GROUP_ID_INVALID;

const gchar LICENSE_UNKNOWN_[] = GST_LICENSE_UNKNOWN;

const Gst::LockFlags LOCK_FLAG_READWRITE_ = (Gst::LockFlags) GST_LOCK_FLAG_READWRITE;

const Gst::MapFlags MAP_READWRITE_ = (Gst::MapFlags) GST_MAP_READWRITE;

const gchar META_TAG_MEMORY_STR_[] = GST_META_TAG_MEMORY_STR;

const GstClockTimeDiff MSECOND_ = GST_MSECOND;

const GstClockTimeDiff NSECOND_ = GST_NSECOND;

const gint PARAM_CONDITIONALLY_AVAILABLE_ = GST_PARAM_CONDITIONALLY_AVAILABLE;

const gint PARAM_CONTROLLABLE_ = GST_PARAM_CONTROLLABLE;

const gint PARAM_DOC_SHOW_DEFAULT_ = GST_PARAM_DOC_SHOW_DEFAULT;

const gint PARAM_MUTABLE_PAUSED_ = GST_PARAM_MUTABLE_PAUSED;

const gint PARAM_MUTABLE_PLAYING_ = GST_PARAM_MUTABLE_PLAYING;

const gint PARAM_MUTABLE_READY_ = GST_PARAM_MUTABLE_READY;

const gint PARAM_USER_SHIFT_ = GST_PARAM_USER_SHIFT;

const gchar PROTECTION_SYSTEM_ID_CAPS_FIELD_[] = GST_PROTECTION_SYSTEM_ID_CAPS_FIELD;

const gchar PROTECTION_UNSPECIFIED_SYSTEM_ID_[] = GST_PROTECTION_UNSPECIFIED_SYSTEM_ID;

const gchar PTR_FORMAT_[] = GST_PTR_FORMAT;

const gint QUERY_NUM_SHIFT_ = GST_QUERY_NUM_SHIFT;

const Gst::QueryTypeFlags QUERY_TYPE_BOTH_ = (Gst::QueryTypeFlags) GST_QUERY_TYPE_BOTH;

const GstClockTimeDiff SECOND_ = GST_SECOND;

const gchar SEGMENT_FORMAT_[] = GST_SEGMENT_FORMAT;

const gint SEGMENT_INSTANT_FLAGS_ = GST_SEGMENT_INSTANT_FLAGS;

const gint SEQNUM_INVALID_ = GST_SEQNUM_INVALID;

const gchar STIMEP_FORMAT_[] = GST_STIMEP_FORMAT;

const gchar STIME_FORMAT_[] = GST_STIME_FORMAT;

const gchar TAG_ALBUM_[] = GST_TAG_ALBUM;

const gchar TAG_ALBUM_ARTIST_[] = GST_TAG_ALBUM_ARTIST;

const gchar TAG_ALBUM_ARTIST_SORTNAME_[] = GST_TAG_ALBUM_ARTIST_SORTNAME;

const gchar TAG_ALBUM_GAIN_[] = GST_TAG_ALBUM_GAIN;

const gchar TAG_ALBUM_PEAK_[] = GST_TAG_ALBUM_PEAK;

const gchar TAG_ALBUM_SORTNAME_[] = GST_TAG_ALBUM_SORTNAME;

const gchar TAG_ALBUM_VOLUME_COUNT_[] = GST_TAG_ALBUM_VOLUME_COUNT;

const gchar TAG_ALBUM_VOLUME_NUMBER_[] = GST_TAG_ALBUM_VOLUME_NUMBER;

const gchar TAG_APPLICATION_DATA_[] = GST_TAG_APPLICATION_DATA;

const gchar TAG_APPLICATION_NAME_[] = GST_TAG_APPLICATION_NAME;

const gchar TAG_ARTIST_[] = GST_TAG_ARTIST;

const gchar TAG_ARTIST_SORTNAME_[] = GST_TAG_ARTIST_SORTNAME;

const gchar TAG_ATTACHMENT_[] = GST_TAG_ATTACHMENT;

const gchar TAG_AUDIO_CODEC_[] = GST_TAG_AUDIO_CODEC;

const gchar TAG_BEATS_PER_MINUTE_[] = GST_TAG_BEATS_PER_MINUTE;

const gchar TAG_BITRATE_[] = GST_TAG_BITRATE;

const gchar TAG_CODEC_[] = GST_TAG_CODEC;

const gchar TAG_COMMENT_[] = GST_TAG_COMMENT;

const gchar TAG_COMPOSER_[] = GST_TAG_COMPOSER;

const gchar TAG_COMPOSER_SORTNAME_[] = GST_TAG_COMPOSER_SORTNAME;

const gchar TAG_CONDUCTOR_[] = GST_TAG_CONDUCTOR;

const gchar TAG_CONTACT_[] = GST_TAG_CONTACT;

const gchar TAG_CONTAINER_FORMAT_[] = GST_TAG_CONTAINER_FORMAT;

const gchar TAG_COPYRIGHT_[] = GST_TAG_COPYRIGHT;

const gchar TAG_COPYRIGHT_URI_[] = GST_TAG_COPYRIGHT_URI;

const gchar TAG_DATE_[] = GST_TAG_DATE;

const gchar TAG_DATE_TIME_[] = GST_TAG_DATE_TIME;

const gchar TAG_DESCRIPTION_[] = GST_TAG_DESCRIPTION;

const gchar TAG_DEVICE_MANUFACTURER_[] = GST_TAG_DEVICE_MANUFACTURER;

const gchar TAG_DEVICE_MODEL_[] = GST_TAG_DEVICE_MODEL;

const gchar TAG_DURATION_[] = GST_TAG_DURATION;

const gchar TAG_ENCODED_BY_[] = GST_TAG_ENCODED_BY;

const gchar TAG_ENCODER_[] = GST_TAG_ENCODER;

const gchar TAG_ENCODER_VERSION_[] = GST_TAG_ENCODER_VERSION;

const gchar TAG_EXTENDED_COMMENT_[] = GST_TAG_EXTENDED_COMMENT;

const gchar TAG_GENRE_[] = GST_TAG_GENRE;

const gchar TAG_GEO_LOCATION_CAPTURE_DIRECTION_[] = GST_TAG_GEO_LOCATION_CAPTURE_DIRECTION;

const gchar TAG_GEO_LOCATION_CITY_[] = GST_TAG_GEO_LOCATION_CITY;

const gchar TAG_GEO_LOCATION_COUNTRY_[] = GST_TAG_GEO_LOCATION_COUNTRY;

const gchar TAG_GEO_LOCATION_ELEVATION_[] = GST_TAG_GEO_LOCATION_ELEVATION;

const gchar TAG_GEO_LOCATION_HORIZONTAL_ERROR_[] = GST_TAG_GEO_LOCATION_HORIZONTAL_ERROR;

const gchar TAG_GEO_LOCATION_LATITUDE_[] = GST_TAG_GEO_LOCATION_LATITUDE;

const gchar TAG_GEO_LOCATION_LONGITUDE_[] = GST_TAG_GEO_LOCATION_LONGITUDE;

const gchar TAG_GEO_LOCATION_MOVEMENT_DIRECTION_[] = GST_TAG_GEO_LOCATION_MOVEMENT_DIRECTION;

const gchar TAG_GEO_LOCATION_MOVEMENT_SPEED_[] = GST_TAG_GEO_LOCATION_MOVEMENT_SPEED;

const gchar TAG_GEO_LOCATION_NAME_[] = GST_TAG_GEO_LOCATION_NAME;

const gchar TAG_GEO_LOCATION_SUBLOCATION_[] = GST_TAG_GEO_LOCATION_SUBLOCATION;

const gchar TAG_GROUPING_[] = GST_TAG_GROUPING;

const gchar TAG_HOMEPAGE_[] = GST_TAG_HOMEPAGE;

const gchar TAG_IMAGE_[] = GST_TAG_IMAGE;

const gchar TAG_IMAGE_ORIENTATION_[] = GST_TAG_IMAGE_ORIENTATION;

const gchar TAG_INTERPRETED_BY_[] = GST_TAG_INTERPRETED_BY;

const gchar TAG_ISRC_[] = GST_TAG_ISRC;

const gchar TAG_KEYWORDS_[] = GST_TAG_KEYWORDS;

const gchar TAG_LANGUAGE_CODE_[] = GST_TAG_LANGUAGE_CODE;

const gchar TAG_LANGUAGE_NAME_[] = GST_TAG_LANGUAGE_NAME;

const gchar TAG_LICENSE_[] = GST_TAG_LICENSE;

const gchar TAG_LICENSE_URI_[] = GST_TAG_LICENSE_URI;

const gchar TAG_LOCATION_[] = GST_TAG_LOCATION;

const gchar TAG_LYRICS_[] = GST_TAG_LYRICS;

const gchar TAG_MAXIMUM_BITRATE_[] = GST_TAG_MAXIMUM_BITRATE;

const gchar TAG_MIDI_BASE_NOTE_[] = GST_TAG_MIDI_BASE_NOTE;

const gchar TAG_MINIMUM_BITRATE_[] = GST_TAG_MINIMUM_BITRATE;

const gchar TAG_NOMINAL_BITRATE_[] = GST_TAG_NOMINAL_BITRATE;

const gchar TAG_ORGANIZATION_[] = GST_TAG_ORGANIZATION;

const gchar TAG_PERFORMER_[] = GST_TAG_PERFORMER;

const gchar TAG_PREVIEW_IMAGE_[] = GST_TAG_PREVIEW_IMAGE;

const gchar TAG_PRIVATE_DATA_[] = GST_TAG_PRIVATE_DATA;

const gchar TAG_PUBLISHER_[] = GST_TAG_PUBLISHER;

const gchar TAG_REFERENCE_LEVEL_[] = GST_TAG_REFERENCE_LEVEL;

const gchar TAG_SERIAL_[] = GST_TAG_SERIAL;

const gchar TAG_SHOW_EPISODE_NUMBER_[] = GST_TAG_SHOW_EPISODE_NUMBER;

const gchar TAG_SHOW_NAME_[] = GST_TAG_SHOW_NAME;

const gchar TAG_SHOW_SEASON_NUMBER_[] = GST_TAG_SHOW_SEASON_NUMBER;

const gchar TAG_SHOW_SORTNAME_[] = GST_TAG_SHOW_SORTNAME;

const gchar TAG_SUBTITLE_CODEC_[] = GST_TAG_SUBTITLE_CODEC;

const gchar TAG_TITLE_[] = GST_TAG_TITLE;

const gchar TAG_TITLE_SORTNAME_[] = GST_TAG_TITLE_SORTNAME;

const gchar TAG_TRACK_COUNT_[] = GST_TAG_TRACK_COUNT;

const gchar TAG_TRACK_GAIN_[] = GST_TAG_TRACK_GAIN;

const gchar TAG_TRACK_NUMBER_[] = GST_TAG_TRACK_NUMBER;

const gchar TAG_TRACK_PEAK_[] = GST_TAG_TRACK_PEAK;

const gchar TAG_USER_RATING_[] = GST_TAG_USER_RATING;

const gchar TAG_VERSION_[] = GST_TAG_VERSION;

const gchar TAG_VIDEO_CODEC_[] = GST_TAG_VIDEO_CODEC;

const gchar TIMEP_FORMAT_[] = GST_TIMEP_FORMAT;

const gchar TIME_FORMAT_[] = GST_TIME_FORMAT;

const gint TOC_REPEAT_COUNT_INFINITE_ = GST_TOC_REPEAT_COUNT_INFINITE;

const gint URI_NO_PORT_ = GST_URI_NO_PORT;

const GstClockTimeDiff USECOND_ = GST_USECOND;

const gint VALUE_EQUAL_ = GST_VALUE_EQUAL;

const gint VALUE_GREATER_THAN_ = GST_VALUE_GREATER_THAN;

const gint VALUE_LESS_THAN_ = GST_VALUE_LESS_THAN;

const gint VALUE_UNORDERED_ = GST_VALUE_UNORDERED;

const gint VERSION_MAJOR_ = GST_VERSION_MAJOR;

const gint VERSION_MICRO_ = GST_VERSION_MICRO;

const gint VERSION_MINOR_ = GST_VERSION_MINOR;

const gint VERSION_NANO_ = GST_VERSION_NANO;

} // namespace Gst

} // namespace repository

} // namespace gi

#endif
